name: Build full project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      run: |
        rustup update stable
        rustup default stable
        nvm install node --lts
        nvm use node --lts
        npm i -g yarn
    - name: build
      run: make
