name: Everything Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v3
    - run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustup component add clippy
        rustup component add rustfmt
    - name: Check
      run: |
        cd blackheap-modeller
        cargo check
    - name: Run clippy
      run: |
        cd blackheap-modeller
        cargo clippy -- -Dwarnings
    - name: Run Fmt
      run: |
        cd blackheap-modeller
        cargo fmt --check

