name: Everything Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        rustup update
        rustup component add clippy
        rustup component add rustfmt
    - name: Check
      working-directory: ./blackheap-modeller
      run: cargo check
    - name: Run clippy
      working-directory: ./blackheap-modeller
      run: cargo clippy -- -Dwarnings
    - name: Run Fmt
      working-directory: ./blackheap-modeller
      run: cargo fmt --check

