name: Ported Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: rust-latest
    steps:
    - name: Lint with clippy
      run: |
        rustup component add clippy && cargo clippy -- -D warnings
  rustfmt:
    runs-on: rust-latest
    steps:
    - name: Lint with rustfmt
      run: |
        rustup component add rustfmt && cargo fmt -- --check

